on:
  pull_request:
    branches:
      - develop
      - master
name: Analyse & Test
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.0'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug